# Generated by Django 4.2.2 on 2023-06-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ID', 'indoor'), ('OD', 'outdoor'), ('OF', 'office'), ('BL', 'balcony'), ('LR', 'living_room'), ('MD', 'medicinal'), ('HD', 'hedge'), ('HP', 'hanging_plant'), ('FB', 'flowering_bulb'), ('FS', 'flower_seed'), ('HS', 'herb_seed'), ('VS', 'vegitable_seed'), ('MG', 'microgreens'), ('CP', 'Cane_Pots'), ('CR', 'ceramic_Pots'), ('CO', 'coco_Pots'), ('CC', 'concrete_Pots'), ('GP', 'glass_Pots'), ('GB', 'grow_bag'), ('HG', 'hanging_Pots'), ('MP', 'metal_Pots'), ('RP', 'resin_pot'), ('SG', 'smart_garden'), ('TC', 'terracotta'), ('WP', 'wooden_Pots'), ('FL', 'fertiliser'), ('GK', 'grow_kit'), ('PC', 'pesticide'), ('PS', 'pot_stand'), ('PM', 'potting_media'), ('TE', 'tools&equipments'), ('AP', 'artificial_plants'), ('BC', 'birds_corner'), ('FG', 'fairy_garden'), ('GA', 'garden_art'), ('GL', 'garden_lights'), ('MT', 'miniature'), ('MF', 'moss_frames'), ('TK', 'terrarium_kit'), ('WF', 'water_fountain')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
