# Generated by Django 4.2.2 on 2023-07-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
